# Setup
title:        Pat Marks
tagline:      "Stuff"
baseurl:
paginate:     5

# About/contact
author:
  name:       Pat Marks
  url:        http://patmarks.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
