# Setup
title:        Pat Marks
tagline:      
baseurl:      "/"
paginate:     1

# About/contact
author:
  name:       Pat Marks
  url:        http://patmarks.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
